# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weights.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweights.proto\x12\x04gpt2\"y\n\x06Weight\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12*\n\nplaintexts\x18\x02 \x03(\x0b\x32\x16.gpt2.Weight.Plaintext\x12\x0b\n\x03\x64im\x18\x03 \x03(\x05\x1a\x1a\n\tPlaintext\x12\r\n\x05value\x18\x01 \x03(\x02\x42\x07\n\x05_name\"n\n\x07Weights\x12\'\n\x05value\x18\x01 \x03(\x0b\x32\x18.gpt2.Weights.ValueEntry\x1a:\n\nValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.gpt2.Weight:\x02\x38\x01\x42\x03\xf8\x01\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weights_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\000'
  _WEIGHTS_VALUEENTRY._options = None
  _WEIGHTS_VALUEENTRY._serialized_options = b'8\001'
  _WEIGHT._serialized_start=23
  _WEIGHT._serialized_end=144
  _WEIGHT_PLAINTEXT._serialized_start=109
  _WEIGHT_PLAINTEXT._serialized_end=135
  _WEIGHTS._serialized_start=146
  _WEIGHTS._serialized_end=256
  _WEIGHTS_VALUEENTRY._serialized_start=198
  _WEIGHTS_VALUEENTRY._serialized_end=256
# @@protoc_insertion_point(module_scope)
